Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: Build and push docker image to ECR and deploy to EKS
+name: Build and push Docker image to ECR and deploy to EKS
 on:
   push:
     branches: [ "main" ]
@@ -20,19 +20,31 @@ jobs:
         aws-region: us-east-1
 
     - name: Login to Amazon ECR
+      id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1
+
+    - name: Print ECR Registry URL
+      run: echo "Registry URL: ${{ steps.login-ecr.outputs.registry }}"
 
     - name: Build, tag, and push docker image to Amazon ECR
       env:
+        AWS_DEFAULT_REGION: us-east-1
+        AWS_REGION: us-east-1
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         REPOSITORY: pranaydevopshelm
         IMAGE_TAG: ${{ github.sha }}
       run: |
+        if [ -z "$REGISTRY" ]; then
+          echo "ERROR: REGISTRY is not set."
+          exit 1
+        fi
         docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
         docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
 
     - name: Update kube config
-      run: aws eks update-kubeconfig --name demo
+      run: aws eks update-kubeconfig --name demo  # Replace 'demo' with your cluster name
 
     - name: Deploy nodejs helm chart to EKS
       run: |
